[project]
name = "fpp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "coreforecast>=0.0.16",
    "fpppy>=0.0.3",
    "ipykernel>=7.2.0",
    "nixtla>=0.7.2",
    "pandas>=3.0.1",
    "seaborn>=0.13.2",
]
